import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { MdHomeFilled, MdSettings, MdList } from "react-icons/md";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
  themeColor: "light",
};

export const metadata: Metadata = {
  title: "Animalets",
  description: "Generated by create next app",
  generator: "Next.js",
  manifest: "/manifest.json",
  keywords: ["nextjs", "nextjs13", "next13", "pwa", "next-pwa"],
  authors: [
    { name: "Albert B" },
    {
      name: "Albert B",
      url: "https://github.com/abonmassip",
    },
  ],
  icons: [
    { rel: "apple-touch-icon", url: "icon-192x192.png" },
    { rel: "icon", url: "icon-192x192.png" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ca" data-theme="retro">
      <body className={`${inter.className} max-w-4xl mx-auto`}>
        <div className="hidden md:flex navbar bg-base-100">
          <Link className="btn btn-ghost text-xl" href="/">
            Inici
          </Link>
          <Link className="btn btn-ghost text-xl" href="/animals">
            Mascotes
          </Link>
          <Link className="btn btn-ghost text-xl ml-auto" href="/settings">
            Configuració
          </Link>
        </div>
        <div className="navbar fixed md:hidden bg-base-200 md:bg-base-100 bottom-0 left-0 flex justify-around">
          <Link className="btn btn-ghost text-xl bg-base-300" href="/">
            <MdHomeFilled />
          </Link>
          <Link className="btn btn-ghost text-xl bg-base-300" href="/animals">
            <MdList />
          </Link>
          <Link className="btn btn-ghost text-xl bg-base-300" href="/settings">
            <MdSettings />
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
