import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
  themeColor: "light",
};

export const metadata: Metadata = {
  title: "Animalets",
  description: "Generated by create next app",
  generator: "Next.js",
  manifest: "/manifest.json",
  keywords: ["nextjs", "nextjs13", "next13", "pwa", "next-pwa"],
  authors: [
    { name: "Albert B" },
    {
      name: "Albert B",
      url: "https://github.com/abonmassip",
    },
  ],
  icons: [
    { rel: "apple-touch-icon", url: "icons/icon-128x128.png" },
    { rel: "icon", url: "icons/icon-128x128.png" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ca" data-theme="retro">
      <body className={`${inter.className} max-w-4xl mx-auto`}>
        <div className="navbar bg-base-100">
          <Link className="btn btn-ghost text-xl" href="/">
            Inici
          </Link>
          {/* <a className="btn btn-ghost text-xl" href="/animals">
            La teva llista de mascotes
          </a> */}
        </div>
        {children}
      </body>
    </html>
  );
}
